# mkdocs.yml
site_name: Lyz's Docs
site_description: 我的技术笔记与知识库
site_url: https://dynamicgraphinfluencemaximization.mmgg.dpdns.org/
site_author: Lyz

# 主题配置
theme:
  name: material
  language: zh
  icon:
    logo:material/github


  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.tabs
    - content.toc
    - content.math
    - content.tooltips
    - search.suggest
    - search.highlight

  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: 切换亮暗模式
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off
        name: 切换亮暗模式

# 导航结构
nav:
  - 首页: index.md
  - 快速入门:
    - 入门指南: getting-started.md
    - 安装说明: installation.md
  - 核心技术:
    - Python: python/index.md
    - 数据分析: data-analysis/index.md
  - API 文档: api-reference.md
  - 关于我们: about.md

# 插件（修复：移除有问题的插件）
plugins:
  - search
  # - minify  # ❌ 注释掉，除非你安装了 mkdocs-minify-plugin
  # - git-revision-date-localized  # 可选：显示最后更新时间（需安装）
  # - mkdocstrings  # ❌ 注释掉，除非你需要 API 自动生成

# 额外资源
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - javascripts/mathjax-config.js  # 可选，确保文件存在再启用

# 额外信息
extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/yourprofile
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourhandle